### ISSUE TITLE
Document Attributes

### ISSUE THREAD

**Issue by shakna-israel** [shakna-israel/doccu#4]
Documents generated will need a number of attributes, that will then be used by either the RESTful API or the templating engine.

Attributes Needed:
- ~~Document Name~~
- ~~Generated Date (when the document was first created)~~
- ~~Date of Authority (when the document becomes active)~~
- ~~Date of Signing (when the document was approved)~~
- ~~Date of Expiration (when the document needs to be re-signed or updated)~~
- ~~Signee (the user who authenticated the document)~~
- ~~Writer/s (the user/s who created the document)~~
- ~~Version (the version of the document)~~
- ~~Status (Current, Out-Of-Date, refers to Version)~~ **Not required**
- ~~Categories (what areas does the document apply to)~~
- ~~Applicable User Groups (what user groups does the document directly impact)~~
- ~~Authorised User Groups (what user groups can update and/or sign the document).~~

**Comment by shakna-israel** [comment]
Structure:

``` yaml
---
- version: 0.0.1
  name: Test Document 0
  author: James Milne
  signer: James Milne
  group: Super Administrators
  authgroup: Super Administrators
  category: doccu
  timestamp: 01/01/2015 00:00:00
  signdate: 01/01/2015 02:04:18
  authdate: 01/01/2016 00:00:00
  expdate: 01/01/2017 00:00:00
  body: |
    # First Subtitle

    This is just a little bit of a paragraph.

    I'm not sure if we'll store in Markdown or in HTML.

    Markdown is much easier to read, but HTML will store much better. No problems with broken lines.
```
